import { StyleSheet } from 'react-native';
import { colors } from '@/theme/theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  header: {
    height: 68,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  backButton: { marginRight: 10 },
  profileButton: { flex: 1, flexDirection: 'row', alignItems: 'center' },
  headerCopy: { flex: 1, marginLeft: 11 },
  headerName: { fontSize: 16, fontWeight: '800', color: colors.text },
  status: { fontSize: 12, color: colors.success, marginTop: 2 },
  keyboard: { flex: 1 },
  messages: { paddingHorizontal: 16, paddingVertical: 20 },
  messageGap: { height: 10 },
  bubbleLine: { flexDirection: 'row' },
  incomingLine: { justifyContent: 'flex-start' },
  outgoingLine: { justifyContent: 'flex-end' },
  bubble: {
    maxWidth: '82%',
    paddingHorizontal: 15,
    paddingTop: 11,
    paddingBottom: 8,
    borderRadius: 18,
  },
  incomingBubble: {
    backgroundColor: colors.surface,
    borderBottomLeftRadius: 5,
  },
  outgoingBubble: {
    backgroundColor: colors.primary,
    borderBottomRightRadius: 5,
  },
  body: { fontSize: 15, lineHeight: 21, color: colors.text },
  outgoingBody: { color: colors.white },
  bubbleMeta: {
    fontSize: 10,
    color: colors.textMuted,
    marginTop: 5,
    alignSelf: 'flex-end',
  },
  outgoingMeta: { color: colors.primaryContrastMuted },
  blockedNotice: {
    paddingHorizontal: 18,
    paddingVertical: 8,
    fontSize: 12,
    textAlign: 'center',
    color: colors.danger,
  },
  composer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
    backgroundColor: colors.surface,
  },
  input: {
    flex: 1,
    minHeight: 44,
    maxHeight: 110,
    borderRadius: 22,
    backgroundColor: colors.background,
    color: colors.text,
    fontSize: 15,
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  send: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendDisabled: { opacity: 0.38 },
  sendPressed: { transform: [{ scale: 0.95 }] },
});
